apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python
    name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
      name: python-app 
  template:
    metadata:
      name: python-app
      labels:
        app: python
        name: python-app
    spec:
      containers:
       - name: python-app
         image: gcr.io/active-sun-337308/python-app:latest
         ports:
          - containerPort: 8000
         env:
          - name: ENVIRONMENT
            value: "DEV"
          - name: HOST
            value: "localhost"
          - name: PORT
            value: "8000"
          - name: REDIS_HOST
            value: "moselhy"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_DB
            value: "0"